language: cpp

script:
- cmake -H. -B_build -DCPACK_GENERATOR="TGZ"
- cmake --build _build --target package
- cmake -H. -B_build -DCPACK_GENERATOR="DEB"
- cmake --build _build --target package


addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data

deploy:
  provider: releases
  api_key: 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
  file: print-0.1.0.0-Linux.deb
  skip_cleanup: true
  on:
    tags: true
